name: Prepare Build Environment
description: Installs required JDKs for building and testing
runs:
  using: "composite"
  steps:
  - name: 'Set up JDK 8'
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: 8
  - name: Prepare JDK8 env var
    shell: bash
    run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
  - name: 'Setup Gradle Build'
    uses: gradle/gradle-build-action@v2
